version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  init:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv .devops-capstone
            source .devops-capstone/bin/activate
            mkdir bin
            echo test > ./bin/test.txt
            ls
            chmod +x bin/*
            chmod +x ./scripts/*
            make install
      - save_cache:
          paths:
            - ./.devops-capstone
          key: v1-dependencies-{{ checksum "src/requirements.txt" }}
      - run:
          name: Run lint
          command: |
            ls bin
            source .devops-capstone/bin/activate
            make lint

workflows:
  default:
    jobs:
      - init        
      - docker/publish:
          matrix:
            parameters:
              image: [dungtnt2244/hello-app]
              path: [hello_app]
              docker-context: [hello_app]
              deploy: [true]
              tag: ['$(<hello_app/VERSION.txt)', 'latest']
              update-description: [true]    
          requires: [init]