version: 2.1

jobs:
  init:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: example
          command: |
            echo hello world

workflows:
  default:
    jobs:
      - init